package com.coremobile.coreyhealth.networkutils;

/**
 * Created by Nitij on 20/04/2016.
 */
public interface ThreadTaskIds {
    int GET_SURVEY = 101;
    int SAVE_SURVEY = 102;

    int GET_REMINDER_STAGE = 201;
    int GET_REMINDER_FREQUENCY = 202;
    int GET_REMINDER_TYPE = 203;
    int SAVE_REMINDER = 204;
    int USE_EXISTING_REMINDER = 205;
    int GET_REMINDER = 206;
    int DELETE_REMINDER = 207;

    int GET_ASSIGNMENT_TYPES = 300;
    int GET_PATIENT_BY_PROVIDER = 301;
    int GET_ASSIGN_ROLES = 302;
    int SAVE_ASSIGN_TO_PATIENT = 303;
    int GET_ASSIGNMENTS_FOR_PATIENT = 304;
    int GET_ALL_PROVIDERS = 305;
    int SAVE_AUTO_ASSIGNMENT = 306;
    int SAVE_ASSIGNMENT_BY_STAFF = 307;
    int GET_OR_USERS = 308;
    int GET_NURSES_TO_OR_ASSIGNMENTS = 309;
    int SAVE_ASSIGN_NURSE_TO_OR = 310;
    int GET_HOSPITAL_DEPARTMENTS = 311;
    int GET_ASSIGNMENT_FOR_FACILITY = 312;
    int SAVE_ASSIGNMENT_FOR_FACILITY = 313;
    int GET_PATIENT_OR_ASSIGNMENT = 314;
    int SAVE_PATIENT_OR_ASSIGNMENT = 315;
    int GET_SPECIALITY = 316;
    int GET_SPECIALITY_OR_ASSIGNMENT = 317;
    int SAVE_SPECIALITY_OR_ASSIGNMENT = 318;

    int GET_PATIENT_NURES_ASSIGNMENT = 319;
    int SAVE_ASSIGN_NURSE_T0_PATIENT = 320;

    int GET_PREVIOUS_CRNA_TO_OR_ASSIGNMENT = 321;

    int GET_EPROS_LIST = 401;
    int SAVE_EPROS = 402;
    int DELETE_EPROS = 403;

    int GET_ACTIVITY_LOG = 501;

    int GET_LOOKUP_DATA = 601;
    int GET_LIST_ITEM = 602;
    int GET_CALENDAR_DATA = 603;
    int GET_SCHEDULE_DATA = 604;
    int UPDATE_SCHEDULE_DATA = 605;
    int GET_LIST_ITEM_MODALITIES = 606;
}
